import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
print("✅ Pollution analysis script is running...")
df=pd.read_csv("HDHI Pollution Data.csv")
print("\n📊 Pollution Data columns:")
print(df.columns)
df['DATE']=pd.to_datetime(df['DATE'],dayfirst=True,errors='coerce')
plt.figure(figsize=(12,6))
sns.lineplot(data=df,x='DATE',y='AQI',marker='o')
plt.title('AQI Trend Over Time')
plt.xlabel('Date')
plt.ylabel('AQI')
plt.grid(True)
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 5))
sns.histplot(df['PM2.5 AVG'], bins=30, kde=True, color='tomato')
plt.title('Distribution of PM2.5 Average Levels')
plt.xlabel('PM2.5 (µg/m³)')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()
pollutants=['PM2.5 AVG','PM10 AVG','NO2 AVG','NH3 AVG','SO2 AVG','CO AVG','OZONE AVG']
plt.figure(figsize=(12,6))
sns.boxplot(data=df[pollutants])
plt.title('Pollutant Levels Distribution')
plt.ylabel('Concentration (µg/m³ or mg/m³)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
plt.figure(figsize=(10, 8))
corr=df[pollutants].corr()
sns.heatmap(corr,annot=True,cmap='coolwarm',vmin=-1,vmax=1)
plt.title('Correlation Heatmap Between Major Pollutants')
plt.tight_layout()
plt.show()
if 'MAX TEMP' in df.columns:
    plt.figure(figsize=(12, 6))
    sns.lineplot(data=df, x='DATE', y='MAX TEMP', marker='o', color='orangered')
    plt.title('Daily Maximum Temperature Trend')
    plt.xlabel('Date')
    plt.ylabel('Max Temperature (°C)')
    plt.grid(True)
    plt.tight_layout()
    plt.show()
print("\n✅ Pollution data analysis completed.")